// SPDX-License-Identifier: Apache-2.0

/**
 * Res ex Machina — Quick Start Demo
 *
 * Demonstrates how an AI Agent generates a Proof of Generation (PoG v1),
 * signs it cryptographically using EIP-712 with its wallet, and registers
 * a verifiable trail of its creation.
 *
 * Run with: npx tsx examples/quick-start-demo.ts
 */

import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { createHash } from 'node:crypto';

// 1. Generate identity for the AI Agent (Ephemeral wallet for demo)
const privateKey = generatePrivateKey();
const agentAccount = privateKeyToAccount(privateKey);

console.log('---------------------------------------------------------');
console.log('🤖 RES EX MACHINA — AI GENERATION REGISTRATION DEMO');
console.log('---------------------------------------------------------');
console.log(`Agent Identity (Wallet): ${agentAccount.address}`);

// 2. Simulated AI Content Generation
const aiGeneratedOutput = `
function calculateSolarOutput(panelAreaM2: number, efficiency: number = 0.20): number {
    // Generated by AI Agent 'SolarBot-v1' at ${new Date().toISOString()}
    const avgIrradianceKwM2 = 1.35; // Peak sunlight irradiance
    return panelAreaM2 * avgIrradianceKwM2 * efficiency;
}
`.trim();

console.log('\n📄 Generated Content (Snippet):');
console.log(aiGeneratedOutput);

// 3. Hash the generated output (SHA-256)
const contentHash = '0x' + createHash('sha256').update(aiGeneratedOutput, 'utf8').digest('hex');
console.log(`\n🔑 Content SHA-256 Hash: ${contentHash}`);

// 4. EIP-712 Domain and Types for Proof of Generation (PoG v1)
const eip712Domain = {
    name: 'ResExMachina',
    version: '1',
    chainId: 84532, // Base Sepolia Testnet
    verifyingContract: '0x0000000000000000000000000000000000000000' as const,
};

const eip712Types = {
    ProofOfGeneration: [
        { name: 'content_hash', type: 'bytes32' },
        { name: 'timestamp', type: 'uint64' },
        { name: 'process_type', type: 'string' },
    ],
};

const timestamp = Math.floor(Date.now() / 1000);
const processType = 'fully_autonomous';

// 5. Sign the Proof of Generation with the Agent's private key
const message = {
    content_hash: contentHash as `0x${string}`,
    timestamp: BigInt(timestamp),
    process_type: processType,
};

async function runDemo() {
    const signature = await agentAccount.signTypedData({
        domain: eip712Domain,
        types: eip712Types,
        primaryType: 'ProofOfGeneration',
        message,
    });

    console.log(`\n✍️ EIP-712 Cryptographic Signature:`);
    console.log(signature);

    console.log('\n📦 Proof of Generation (PoG v1) Payload:');
    const payload = {
        agent_wallet: agentAccount.address,
        content_hash: contentHash,
        timestamp,
        generation_process: {
            type: processType,
            human_intervention_level: 'none',
            model_identifier: 'gemini-3.6-flash',
        },
        pog_bundle: {
            version: '1.0',
            domain: eip712Domain,
            message: {
                content_hash: contentHash,
                timestamp,
                process_type: processType,
            },
            signature,
        },
    };

    console.log(JSON.stringify(payload, null, 2));
    console.log('\n✅ Demo completed successfully! PoG payload is ready for submission to POST /v1/records.');
    console.log('---------------------------------------------------------');
}

runDemo().catch(console.error);
