[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = []
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10000
bytecode_hash = "none"
